### ISSUE TITLE
Activate ranked functionality

### ISSUE THREAD

**Issue by sct** [jvennik/discord-valorant-meister#21]
There is currently some basic code to deal with user ranks but no actual way to use it yet. Probably need a few things to make this work.

- A command to let users set their rank: `!valorant rank <rankname>` (Ranks will be simple like iron1, iron2, iron3, etc)
- When creating an event, the user's rank will be taken into account when it's created. An optional argument can only be passed in to set it as unranked. `!valorant create <name> unranked` ?? Maybe something else? Maybe just `!valorant unranked <event name>`? @jvennik input?

**Comment by jvennik** [comment]
@sct This is just basic support before we get API access to set the rank automatically?

If so:

1. Yeah, that sounds OK. Just need to verify they typed something correctly, not too difficult.
2. Probably the latter `!valorant unranked <event name>` is easier to handle.

**Comment by sct** [comment]
I think we can abandon this ticket now with our plans for the bot? @jvennik

**Comment by jvennik** [comment]
> I think we can abandon this ticket now with our plans for the bot? @jvennik

Might still be valid for certain games to differentiate between ranked and unranked, but I guess we can just solve that by having people put it in the event title instead.
